# -*- coding: utf-8 -*-
"""Deteksi Objek.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YVx64q1_UOZoHzTA-Td4DxuxeLwWrb2w
"""

# Install necessary libraries
!pip install ultralytics

# Import libraries
from ultralytics import YOLO
from google.colab import files
import cv2
import matplotlib.pyplot as plt
import numpy as np

# Upload a video or image for object detection
uploaded = files.upload()

# Load the YOLO model (pre-trained weights)
model = YOLO("yolov8n.pt")  # You can use yolov8s.pt or other variants based on performance needs

# Perform object detection
for file_name in uploaded.keys():
    # Read the image
    img = cv2.imread(file_name)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # Run YOLO detection
    results = model(img)

    # Visualize results
    for result in results:
        annotated_frame = result.plot()
        plt.imshow(annotated_frame)
        plt.axis('off')
        plt.show()